package com.evosys.mersalordergenerator.helperclasses;

import java.util.ArrayList;

/**
 * Created by ehtisham on 2/5/17.
 */

public class AbusiveWords {
    private ArrayList<String> AbusiveWordsList = new ArrayList<>();

    public ArrayList<String> GetWordsList(){
        return AbusiveWordsList;
    }

    public AbusiveWords(){
        AbusiveWordsList.add("2g1c");
        AbusiveWordsList.add("2 girls 1 cup");
        AbusiveWordsList.add("acrotomophilia");
        AbusiveWordsList.add("anal");
        AbusiveWordsList.add("anilingus");
        AbusiveWordsList.add("anus");
        AbusiveWordsList.add("arsehole");
        AbusiveWordsList.add("ass");
        AbusiveWordsList.add("asshole");
        AbusiveWordsList.add("assmunch");
        AbusiveWordsList.add("auto erotic");
        AbusiveWordsList.add("autoerotic");
        AbusiveWordsList.add("babeland");
        AbusiveWordsList.add("baby batter");
        AbusiveWordsList.add("ball gag");
        AbusiveWordsList.add("ball gravy");
        AbusiveWordsList.add("ball kicking");
        AbusiveWordsList.add("ball licking");
        AbusiveWordsList.add("ball sack");
        AbusiveWordsList.add("ball sucking");
        AbusiveWordsList.add("bangbros");
        AbusiveWordsList.add("bareback");
        AbusiveWordsList.add("barely legal");
        AbusiveWordsList.add("barenaked");
        AbusiveWordsList.add("bastardo");
        AbusiveWordsList.add("bastinado");
        AbusiveWordsList.add("bbw");
        AbusiveWordsList.add("bdsm");
        AbusiveWordsList.add("beaver cleaver");
        AbusiveWordsList.add("beaver lips");
        AbusiveWordsList.add("bestiality");
        AbusiveWordsList.add("bi curious");
        AbusiveWordsList.add("big black");
        AbusiveWordsList.add("big breasts");
        AbusiveWordsList.add("big knockers");
        AbusiveWordsList.add("big tits");
        AbusiveWordsList.add("bimbos");
        AbusiveWordsList.add("birdlock");
        AbusiveWordsList.add("bitch");
        AbusiveWordsList.add("black cock");
        AbusiveWordsList.add("blonde action");
        AbusiveWordsList.add("blonde on blonde");
        AbusiveWordsList.add("action");
        AbusiveWordsList.add("blow j");
        AbusiveWordsList.add("blow your l");
        AbusiveWordsList.add("blue waffle");
        AbusiveWordsList.add("blumpkin");
        AbusiveWordsList.add("bollocks");
        AbusiveWordsList.add("bondage");
        AbusiveWordsList.add("boner");
        AbusiveWordsList.add("boob");
        AbusiveWordsList.add("boobs");
        AbusiveWordsList.add("booty call");
        AbusiveWordsList.add("brown showers");
        AbusiveWordsList.add("brunette action");
        AbusiveWordsList.add("bukkake");
        AbusiveWordsList.add("bulldyke");
        AbusiveWordsList.add("bullet vibe");
        AbusiveWordsList.add("bullet vibe");
        AbusiveWordsList.add("bunghole");
        AbusiveWordsList.add("busty");
        AbusiveWordsList.add("butt");
        AbusiveWordsList.add("buttcheeks");
        AbusiveWordsList.add("butthole");
        AbusiveWordsList.add("camel toe");
        AbusiveWordsList.add("camgirl");
        AbusiveWordsList.add("camslut");

        AbusiveWordsList.add("camwhore");
        AbusiveWordsList.add("carpet muncher");
        AbusiveWordsList.add("carpetmuncher");
        AbusiveWordsList.add("chocolate rosebuds");
        AbusiveWordsList.add("circlejerk");
        AbusiveWordsList.add("cleveland steamer");
        AbusiveWordsList.add("clit");
        AbusiveWordsList.add("clitoris");
        AbusiveWordsList.add("clover clamps");
        AbusiveWordsList.add("clusterfuck");
        AbusiveWordsList.add("cock");
        AbusiveWordsList.add("cocks");
        AbusiveWordsList.add("coprolagnia");
        AbusiveWordsList.add("coprophilia");
        AbusiveWordsList.add("cornhole");
        AbusiveWordsList.add("cum");
        AbusiveWordsList.add("cumming");
        AbusiveWordsList.add("cunnilingus");
        AbusiveWordsList.add("cunt");
        AbusiveWordsList.add("darkie");
        AbusiveWordsList.add("date rape");
        AbusiveWordsList.add("daterape");
        AbusiveWordsList.add("deep throat");
        AbusiveWordsList.add("deepthroat");
        AbusiveWordsList.add("dick");
        AbusiveWordsList.add("dildo");
        AbusiveWordsList.add("dirty pillows");
        AbusiveWordsList.add("dirty pillows");
        AbusiveWordsList.add("dog style");
        AbusiveWordsList.add("doggie style");
        AbusiveWordsList.add("doggiestyle");
        AbusiveWordsList.add("doggy style");
        AbusiveWordsList.add("doggystyle");
        AbusiveWordsList.add("dolcett");
        AbusiveWordsList.add("domination");
        AbusiveWordsList.add("dominatrix");
        AbusiveWordsList.add("dommes");
        AbusiveWordsList.add("donkey punch");
        AbusiveWordsList.add("double dong");
        AbusiveWordsList.add("double penetration");
        AbusiveWordsList.add("dp action");
        AbusiveWordsList.add("eat my ass");
        AbusiveWordsList.add("ecchi");
        AbusiveWordsList.add("ejaculation");
        AbusiveWordsList.add("erotic");
        AbusiveWordsList.add("erotism");
        AbusiveWordsList.add("escort");
        AbusiveWordsList.add("ethical slut");
        AbusiveWordsList.add("eunuch");
        AbusiveWordsList.add("faggot");
        AbusiveWordsList.add("fecal");
        AbusiveWordsList.add("felch");
        AbusiveWordsList.add("fellatio");
        AbusiveWordsList.add("feltch");
        AbusiveWordsList.add("female squirting");
        AbusiveWordsList.add("femdom");
        AbusiveWordsList.add("figging");
        AbusiveWordsList.add("fingering");
        AbusiveWordsList.add("fisting");
        AbusiveWordsList.add("foot fetish");
        AbusiveWordsList.add("footjob");
        AbusiveWordsList.add("frotting");
        AbusiveWordsList.add("fuck");
        AbusiveWordsList.add("fucker");
        AbusiveWordsList.add("fucking");
        AbusiveWordsList.add("fuck buttons");
        AbusiveWordsList.add("fudge packer");
        AbusiveWordsList.add("fudgepacker");
        AbusiveWordsList.add("futanari");
        AbusiveWordsList.add("g-spot");

        AbusiveWordsList.add("gang bang");
        AbusiveWordsList.add("gay sex");
        AbusiveWordsList.add("genitals");
        AbusiveWordsList.add("giant cock");
        AbusiveWordsList.add("girl on");
        AbusiveWordsList.add("girl on top");
        AbusiveWordsList.add("girls gone wild");
        AbusiveWordsList.add("goatcx");
        AbusiveWordsList.add("goatse");
        AbusiveWordsList.add("gokkun");
        AbusiveWordsList.add("golden shower");
        AbusiveWordsList.add("goo girl");
        AbusiveWordsList.add("goodpoop");
        AbusiveWordsList.add("goregasm");
        AbusiveWordsList.add("grope");
        AbusiveWordsList.add("group sex");
        AbusiveWordsList.add("guro");
        AbusiveWordsList.add("hand job");
        AbusiveWordsList.add("handjob");
        AbusiveWordsList.add("hard core");
        AbusiveWordsList.add("hardcore");
        AbusiveWordsList.add("hentai");
        AbusiveWordsList.add("homoerotic");
        AbusiveWordsList.add("honkey");
        AbusiveWordsList.add("hooker");
        AbusiveWordsList.add("hot chick");
        AbusiveWordsList.add("how to kill");
        AbusiveWordsList.add("how to murder");
        AbusiveWordsList.add("huge fat");
        AbusiveWordsList.add("humping");
        AbusiveWordsList.add("incest");

        AbusiveWordsList.add("intercourse");
        AbusiveWordsList.add("jack off");
        AbusiveWordsList.add("jail bait");
        AbusiveWordsList.add("jailbait");
        AbusiveWordsList.add("jerk off");
        AbusiveWordsList.add("jigaboo");
        AbusiveWordsList.add("jiggaboo");
        AbusiveWordsList.add("jiggerboo");
        AbusiveWordsList.add("jizz");
        AbusiveWordsList.add("juggs");
        AbusiveWordsList.add("kike");
        AbusiveWordsList.add("kinbaku");
        AbusiveWordsList.add("kinkster");
        AbusiveWordsList.add("kinky");
        AbusiveWordsList.add("knobbing");
        AbusiveWordsList.add("leather restraint");
        AbusiveWordsList.add("leather straight jacket");
        AbusiveWordsList.add("lemon party");
        AbusiveWordsList.add("lolita");
        AbusiveWordsList.add("lovemaking");
        AbusiveWordsList.add("make me come");
        AbusiveWordsList.add("male squirting");
        AbusiveWordsList.add("masturbate");
        AbusiveWordsList.add("menage a trois");
        AbusiveWordsList.add("milf");
        AbusiveWordsList.add("missionary position");
        AbusiveWordsList.add("motherfucker");
        AbusiveWordsList.add("mound of venus");
        AbusiveWordsList.add("mr hands");
        AbusiveWordsList.add("muff diver");
        AbusiveWordsList.add("muffdiving");

        AbusiveWordsList.add("nambla");
        AbusiveWordsList.add("nawashi");
        AbusiveWordsList.add("negro");
        AbusiveWordsList.add("neonazi");
        AbusiveWordsList.add("nig nog");
        AbusiveWordsList.add("nigga");
        AbusiveWordsList.add("nigger");
        AbusiveWordsList.add("nimphomania");
        AbusiveWordsList.add("nipple");
        AbusiveWordsList.add("nipples");
        AbusiveWordsList.add("nsfw images");
        AbusiveWordsList.add("nude");
        AbusiveWordsList.add("nudity");
        AbusiveWordsList.add("nympho");
        AbusiveWordsList.add("nymphomania");
        AbusiveWordsList.add("octopussy");
        AbusiveWordsList.add("omorashi");
        AbusiveWordsList.add("one cup two girls");
        AbusiveWordsList.add("one guy one jar");
        AbusiveWordsList.add("orgasm");
        AbusiveWordsList.add("orgy");
        AbusiveWordsList.add("paedophile");
        AbusiveWordsList.add("panties");
        AbusiveWordsList.add("panty");
        AbusiveWordsList.add("pedobear");
        AbusiveWordsList.add("pedophile");
        AbusiveWordsList.add("pegging");
        AbusiveWordsList.add("penis");
        AbusiveWordsList.add("phone sex");
        AbusiveWordsList.add("piece of shit");
        AbusiveWordsList.add("piss pig");

        AbusiveWordsList.add("pissing");
        AbusiveWordsList.add("playboy");
        AbusiveWordsList.add("pleasure chest");
        AbusiveWordsList.add("pole smoker");
        AbusiveWordsList.add("ponyplay");
        AbusiveWordsList.add("poof");
        AbusiveWordsList.add("poop chute");
        AbusiveWordsList.add("poopchute");
        AbusiveWordsList.add("porn");
        AbusiveWordsList.add("porno");
        AbusiveWordsList.add("pornography");
        AbusiveWordsList.add("prince albert piercing");
        AbusiveWordsList.add("pthc");
        AbusiveWordsList.add("pubes");
        AbusiveWordsList.add("pussy");
        AbusiveWordsList.add("queaf");
        AbusiveWordsList.add("raghead");
        AbusiveWordsList.add("raging boner");
        AbusiveWordsList.add("rape");
        AbusiveWordsList.add("raping");
        AbusiveWordsList.add("rapist");
        AbusiveWordsList.add("rectum");
        AbusiveWordsList.add("reverse cowgirl");
        AbusiveWordsList.add("rimjob");
        AbusiveWordsList.add("rimming");
        AbusiveWordsList.add("rosy palm");
        AbusiveWordsList.add("rosy palm and her 5");
        AbusiveWordsList.add("sisters");
        AbusiveWordsList.add("rusty trombone");
        AbusiveWordsList.add("s&m");
        AbusiveWordsList.add("sadism");

        AbusiveWordsList.add("scat");
        AbusiveWordsList.add("schlong");
        AbusiveWordsList.add("scissoring");
        AbusiveWordsList.add("semen");
        AbusiveWordsList.add("sex");
        AbusiveWordsList.add("sexo");
        AbusiveWordsList.add("sexy");
        AbusiveWordsList.add("shaved beaver");
        AbusiveWordsList.add("shaved pussy");
        AbusiveWordsList.add("shemale");
        AbusiveWordsList.add("shibari");
        AbusiveWordsList.add("shit");
        AbusiveWordsList.add("shitcock");
        AbusiveWordsList.add("shitty");
        AbusiveWordsList.add("shota");
        AbusiveWordsList.add("shrimping");
        AbusiveWordsList.add("slanteye");
        AbusiveWordsList.add("slut");
        AbusiveWordsList.add("smut");
        AbusiveWordsList.add("snatch");
        AbusiveWordsList.add("snowballing");
        AbusiveWordsList.add("sodomize");
        AbusiveWordsList.add("sodomy");
        AbusiveWordsList.add("spic");
        AbusiveWordsList.add("spooge");
        AbusiveWordsList.add("spread legs");
        AbusiveWordsList.add("strap on");
        AbusiveWordsList.add("strapon");
        AbusiveWordsList.add("strappado");
        AbusiveWordsList.add("strip club");
        AbusiveWordsList.add("style doggy");


        AbusiveWordsList.add("suck");
        AbusiveWordsList.add("sucks");
        AbusiveWordsList.add("suicide girls");
        AbusiveWordsList.add("sultry women");
        AbusiveWordsList.add("swastika");
        AbusiveWordsList.add("swinger");
        AbusiveWordsList.add("tainted love");
        AbusiveWordsList.add("taste my");
        AbusiveWordsList.add("tea bagging");
        AbusiveWordsList.add("threesome");
        AbusiveWordsList.add("throating");
        AbusiveWordsList.add("tied up");
        AbusiveWordsList.add("tight white");
        AbusiveWordsList.add("tit");
        AbusiveWordsList.add("tits");
        AbusiveWordsList.add("titties");
        AbusiveWordsList.add("titty");
        AbusiveWordsList.add("tongue in a");
        AbusiveWordsList.add("topless");
        AbusiveWordsList.add("tosser");
        AbusiveWordsList.add("towelhead");
        AbusiveWordsList.add("tranny");
        AbusiveWordsList.add("tribadism");
        AbusiveWordsList.add("tub girl");
        AbusiveWordsList.add("tubgirl");
        AbusiveWordsList.add("tushy");
        AbusiveWordsList.add("twat");
        AbusiveWordsList.add("twink");
        AbusiveWordsList.add("twinkie");
        AbusiveWordsList.add("two girls one cup");
        AbusiveWordsList.add("undressing");


        AbusiveWordsList.add("upskirt");
        AbusiveWordsList.add("urethra play");
        AbusiveWordsList.add("urophilia");
        AbusiveWordsList.add("vagina");
        AbusiveWordsList.add("venus mound");
        AbusiveWordsList.add("vibrator");
        AbusiveWordsList.add("violet blue");
        AbusiveWordsList.add("violet wand");
        AbusiveWordsList.add("vorarephilia");
        AbusiveWordsList.add("voyeur");
        AbusiveWordsList.add("vulva");
        AbusiveWordsList.add("wank");
        AbusiveWordsList.add("wet dream");
        AbusiveWordsList.add("wetback");
        AbusiveWordsList.add("white power");
        AbusiveWordsList.add("women rapping");
        AbusiveWordsList.add("wrapping men");
        AbusiveWordsList.add("wrinkled starfish");
        AbusiveWordsList.add("xx");
        AbusiveWordsList.add("xxx");
        AbusiveWordsList.add("yaoi");
        AbusiveWordsList.add("yellow showers");
        AbusiveWordsList.add("yiffy");
        AbusiveWordsList.add("zoophilia");
        AbusiveWordsList.add("طيز");
        AbusiveWordsList.add("كس");
        AbusiveWordsList.add("زب");
        AbusiveWordsList.add("منيوك");
        AbusiveWordsList.add("انيكك");
        AbusiveWordsList.add("أنيكك");
        AbusiveWordsList.add("خرق");


        AbusiveWordsList.add("نيك");
        AbusiveWordsList.add("خرا");
        AbusiveWordsList.add("زق");
    }
}
